export enum DuelWebsocketServerActions {
    JOIN_QUEUE_SUCCESS = 'JOIN_QUEUE_SUCCESS',
    JOIN_QUEUE_FAILURE = 'JOIN_QUEUE_FAILURE',
    LEAVE_QUEUE_SUCCESS = 'LEAVE_QUEUE_SUCCESS',
    OPPONENT_FOUND = 'OPPONENT_FOUND',
    OPPONENT_BANNED_MAP = 'OPPONENT_BANNED_MAP',
    PLAYER_STATE = 'PLAYER_STATE',
}
