export enum DuelWebsocketServerActions {
    JOIN_QUEUE_SUCCESS = 'JOIN_QUEUE_SUCCESS',
    JOIN_QUEUE_FAILURE = 'JOIN_QUEUE_FAILURE',
    LEAVE_QUEUE_SUCCESS = 'LEAVE_QUEUE_SUCCESS',
    PICKBAN_STEP = 'PICKBAN_STEP',
    PLAYER_STATE = 'PLAYER_STATE',
    TIMER_STARTED = 'TIMER_STARTED',
    DUPLICATE_CLIENT = 'DUPLICATE_CLIENT',
}
