import { MapInterface } from '../interfaces/map.interface';

export const maps: MapInterface[] = [
    {
        name: 'r2fast',
        difficulty: 3,
        weapons: 'U',
        vq3Record: 21.768,
        cpmRecord: 8.472,
    },
    {
        name: 'nemix_run01',
        difficulty: 3,
        weapons: 'GRP',
        vq3Record: 44.96,
        cpmRecord: 38.192,
    },
    {
        name: 'tuffrun',
        difficulty: 4,
        weapons: 'U',
        vq3Record: 14.792,
        cpmRecord: 10.416,
    },
    {
        name: 'unwind_run02',
        difficulty: 3,
        weapons: 'GRPB',
        vq3Record: 45.96,
        cpmRecord: 47.784,
    },
    {
        name: 'run_quake',
        difficulty: 3,
        weapons: 'U',
        vq3Record: 51.568,
        cpmRecord: 19.608,
    },
    {
        name: 'run3-diche',
        difficulty: 2,
        weapons: 'GP',
        vq3Record: 15.48,
        cpmRecord: 14.68,
    },
    {
        name: 'imoor_run01',
        difficulty: 5,
        weapons: 'GRP',
        vq3Record: 38.296,
        cpmRecord: 38.728,
    },
    {
        name: 'score',
        difficulty: 3,
        weapons: 'GRP',
        vq3Record: 53.328,
        cpmRecord: 48.464,
    },
    {
        name: 'dsrun2',
        difficulty: 2,
        weapons: 'U',
        vq3Record: 48.76,
        cpmRecord: 42.368,
    },
    {
        name: 'czsk2009-impulse',
        difficulty: 3,
        weapons: 'GRPB',
        vq3Record: 36.736,
        cpmRecord: 31.776,
    },
    {
        name: 'elco-egy',
        difficulty: 5,
        weapons: 'GRPB',
        vq3Record: 50.072,
        cpmRecord: 40.192,
    },
    {
        name: 'imoor_run07',
        difficulty: 3,
        weapons: 'U',
        vq3Record: 35.456,
        cpmRecord: 28.488,
    },
    {
        name: 'pornstar-8percent',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 37.464,
        cpmRecord: 24.456,
    },
    {
        name: 'pornstar-quickie1',
        difficulty: 2,
        weapons: 'U',
        vq3Record: 29.6,
        cpmRecord: 18.176,
    },
    {
        name: 'pdm01_TymoN',
        difficulty: 3,
        weapons: 'RPI',
        vq3Record: 28.424,
        cpmRecord: 27.712,
    },
    {
        name: 'run_Swordfish',
        difficulty: 3,
        weapons: 'RPB',
        vq3Record: 22.456,
        cpmRecord: 16.376,
    },
    {
        name: 'alphamap',
        difficulty: 2,
        weapons: 'RP',
        vq3Record: 33.624,
        cpmRecord: 30.16,
    },
    {
        name: 'frcup34',
        difficulty: 4,
        weapons: 'RP',
        vq3Record: 20.272,
        cpmRecord: 17.328,
    },
    {
        name: 'ghost-pornstar2',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 26.656,
        cpmRecord: 17.008,
    },
    {
        name: 'elco-maze',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 37.36,
        cpmRecord: 22.064,
    },
    {
        name: 'killua-hykon',
        difficulty: 3,
        weapons: 'R',
        vq3Record: 16.168,
        cpmRecord: 9.912,
    },
    {
        name: 'termite',
        difficulty: 4,
        weapons: 'P',
        vq3Record: 32.4,
        cpmRecord: 28.264,
    },
    {
        name: 'yotoon-glados',
        difficulty: 4,
        weapons: 'M',
        vq3Record: 51.96,
        cpmRecord: 39.04,
    },
    {
        name: 'mAndArin_run2',
        difficulty: 3,
        weapons: 'RP',
        vq3Record: 11.888,
        cpmRecord: 10.96,
    },
    {
        name: '2fastcomp001',
        difficulty: 1,
        weapons: 'RPL',
        vq3Record: 6.624,
        cpmRecord: 5.784,
    },
    {
        name: 'effect-bfgrun',
        difficulty: 3,
        weapons: 'B',
        vq3Record: 13.688,
        cpmRecord: 11.992,
    },
    {
        name: 'fu3l3d_rocket',
        difficulty: 2,
        weapons: 'R',
        vq3Record: 7.32,
        cpmRecord: 5.44,
    },
    {
        name: 'cwc01_1',
        difficulty: 3,
        weapons: 'GRP',
        vq3Record: 16.936,
        cpmRecord: 15.512,
    },
    {
        name: 'poon-udc',
        difficulty: 4,
        weapons: 'GRPB',
        vq3Record: 49.408,
        cpmRecord: 32.944,
    },
    {
        name: 'kairos-machine',
        difficulty: 2,
        weapons: 'BSH',
        vq3Record: 25.792,
        cpmRecord: 22.504,
    },
    {
        name: 'r7-spling',
        difficulty: 2,
        weapons: 'GRPBL',
        vq3Record: 41.096,
        cpmRecord: 37.4,
    },
    {
        name: 'n3ur0_icebase',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 38.368,
        cpmRecord: 23.56,
    },
    {
        name: 'ddc2018-stomp',
        difficulty: 5,
        weapons: 'RI',
        vq3Record: 116.848,
        cpmRecord: 81.016,
    },
    {
        name: 'ddc2018-abydos',
        difficulty: 3,
        weapons: 'GRP',
        vq3Record: 31.984,
        cpmRecord: 26.008,
    },
    {
        name: 'ddc2018-enigma',
        difficulty: 1,
        weapons: 'M',
        vq3Record: 23.04,
        cpmRecord: 17,
    },
    {
        name: 'ddc2018-amaranth',
        difficulty: 3,
        weapons: 'GRP',
        vq3Record: 29.072,
        cpmRecord: 23.76,
    },
    {
        name: 'ddc2018-apex',
        difficulty: 3,
        weapons: 'GRP',
        vq3Record: 34.568,
        cpmRecord: 27.512,
    },
    {
        name: 'ddc2018-countach',
        difficulty: 3,
        weapons: 'GR',
        vq3Record: 25.392,
        cpmRecord: 24.72,
    },
    {
        name: 'ddc2018-medieva',
        difficulty: 3,
        weapons: 'GRPB',
        vq3Record: 23.736,
        cpmRecord: 16.544,
    },
    {
        name: 'ddc2018-tryhoard',
        difficulty: 4,
        weapons: 'GRP',
        vq3Record: 64.616,
        cpmRecord: 42.752,
    },
    {
        name: 'cruton2-icy',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 47.912,
        cpmRecord: 20.568,
    },
    {
        name: 'ghost-city',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 24.704,
        cpmRecord: 15.152,
    },
    {
        name: 'daan-spacerox',
        difficulty: 1,
        weapons: 'R',
        vq3Record: 12.112,
        cpmRecord: 9.896,
    },
    {
        name: 'stammer-rocketcave',
        difficulty: 1,
        weapons: 'R',
        vq3Record: 22.848,
        cpmRecord: 16.336,
    },
    {
        name: 'pento-slick',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 38.048,
        cpmRecord: 24.48,
    },
    {
        name: 'coldrun',
        difficulty: 1,
        weapons: 'RP',
        vq3Record: 9.016,
        cpmRecord: 7.744,
    },
    {
        name: 'biotrix-sea',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 23.336,
        cpmRecord: 14.808,
    },
    {
        name: 'f1o_s1',
        difficulty: 1,
        weapons: 'U',
        vq3Record: 19.04,
        cpmRecord: 14.008,
    },
    {
        name: 'thd-final09',
        difficulty: 4,
        weapons: 'GRP',
        vq3Record: 80.728,
        cpmRecord: 68.656,
    },
    {
        name: 'th0ca-isback',
        difficulty: 3,
        vq3Record: 34.136,
        cpmRecord: 28.392,
        weapons: 'P',
    },
    {
        name: 'j4n_mucki',
        difficulty: 3,
        vq3Record: 20.8,
        cpmRecord: 17.216,
        weapons: 'GRP',
    },
    {
        name: 'warcup50-3',
        difficulty: 3,
        vq3Record: 25.024,
        cpmRecord: 23.736,
        weapons: 'GRP',
    },
    {
        name: 'xLarve_df09',
        difficulty: 2,
        vq3Record: 40.912,
        cpmRecord: 35.088,
        weapons: 'GP',
    },
    {
        name: 'bdfcomp026',
        difficulty: 2,
        vq3Record: 7.96,
        cpmRecord: 6.72,
        weapons: 'RP',
    },
    {
        name: 'gdfcomp11',
        difficulty: 2,
        vq3Record: 9.624,
        cpmRecord: 9.392,
        weapons: 'GR',
    },
    {
        name: 'furthy_roomz',
        difficulty: 2,
        vq3Record: 24.24,
        cpmRecord: 18.64,
        weapons: 'R',
    },
    {
        name: 'warrior-rj1',
        difficulty: 3,
        vq3Record: 17.544,
        cpmRecord: 11.975999999999999,
        weapons: 'R',
    },
    {
        name: 'kiccel_cup04',
        difficulty: 3,
        vq3Record: 15.648,
        cpmRecord: 9.48,
        weapons: 'GRP',
    },
    {
        name: 'sdc39',
        difficulty: 2,
        vq3Record: 13.088,
        cpmRecord: 8.328,
        weapons: 'GR',
    },
    {
        name: 'q3dfrun',
        difficulty: 3,
        vq3Record: 23.304,
        cpmRecord: 19.888,
        weapons: 'R',
    },
    {
        name: 'frcup42',
        difficulty: 1,
        vq3Record: 32.88,
        cpmRecord: 22.352,
        weapons: 'U',
    },
    {
        name: 'bdfcomp012',
        difficulty: 2,
        vq3Record: 8.816,
        cpmRecord: 5.5760000000000005,
        weapons: 'GRP',
    },
    {
        name: 'Nlrun-1',
        difficulty: 5,
        vq3Record: 34.832,
        cpmRecord: 30.568,
        weapons: 'GRP',
    },
    {
        name: 'Hydrosorbic',
        difficulty: 5,
        vq3Record: 23.696,
        cpmRecord: 17.432,
        weapons: 'RPB',
    },
    {
        name: 'cruton3',
        difficulty: 2,
        vq3Record: 83.192,
        cpmRecord: 35.344,
        weapons: 'U',
    },
    {
        name: 'gpl-gypt',
        difficulty: 2,
        vq3Record: 39.776,
        cpmRecord: 34.192,
        weapons: 'RP',
    },
    {
        name: 'cross-03-aren',
        difficulty: 5,
        vq3Record: 15.632,
        cpmRecord: 13.904,
        weapons: 'P',
    },
    {
        name: 'j4n_yotoon',
        difficulty: 1,
        vq3Record: 28.616,
        cpmRecord: 17.032,
        weapons: 'U',
    },
    {
        name: 'inder-junk',
        difficulty: 3,
        vq3Record: 35.376,
        cpmRecord: 28.328,
        weapons: 'GRP',
    },
    {
        name: 'e-penetration',
        difficulty: 2,
        vq3Record: 13.8,
        cpmRecord: 9.92,
        weapons: 'R',
    },
    {
        name: 'rockarolla9',
        difficulty: 2,
        vq3Record: 10.048,
        cpmRecord: 8.656,
        weapons: 'R',
    },
    {
        name: 'kabcorp-jel',
        difficulty: 4,
        vq3Record: 47.68,
        cpmRecord: 37.056,
        weapons: 'GRP',
    },
];

// 'effect-combo',
// '0ups-rocketrun1',
// 'grottorush',
// 'Discord',
// 'cmc06_th0ca',
// 'pornstar-thickwoman',
// 'sdc01',
// 'acc_cake',
// 'IDM_Aectroner',
// 'mistes-depot',
// 'Pharaohmones',
// 'crem_brew_lay',
// 'stalker-mirai',
// 'j4n_run3',
// 'IDM_Sobaken',
// 'asda-kartta',
// 'bomfunk2',
// 'effect-hyper',
// 'Rocketque11',
// 'geto',
// 'in_memory_of_gloom',
// 'mistes-wprun04',
// 'Hypertension',
// 'mistes-wprun05',
// 'inder-strangeland',
// 'xLarve_df19',
// 'runzedder-4',
// 'r7-jel',
// 'kabcorp-sousix_is_dead',
// 'rjrunv2',
// 'cupquake',
// 'marvin-waffenlauf2',
// 'spr-gpl',
// 'nood-momentum',
// 'biscuit',
// 'enz-02',
// 'cruton6-rox',
// 'ThotExpress',
// 'th0ca-boring',
// 'run124',
// 'nood-momentum2',
// 'xLarve_df20',
// 'torner2015-heroo',
// 'torner2015-reflex',
// 'monorun',
// 'gloom_comp01',
// 'xt4zy-shorty_huerty01',
// 'RDFCOMP054',
// 'tenuous',
// 'runstolfer-5',
// 'gothrockets',
// 'DFru_mappers_01',
// 'rundsi',
// 'run139',
// 'kairos-returns',
// 'nood-4_den',
// 'Dark-Temple',
// 'lg21',
// 'warcup144',
// 'ruyn',
// 'imoor_run08',
// 'mistes-wprun06',
// 'dfcup09',
// 'runtomb',
// 'RunMesta',
// 'j4n_Strangeland_FULL',
// 'l1th-inder',
// 'IDM_frAkIR',
// 'fe-run_1_rox',
// 'run-brickstonerocket',
// 'nood-acab',
// 'xt4zy_4QL',
// 'j4n_hotrun',
// 'Hellescape',
// 'kabcorp-effect',
// 'ropg',
// 'fe-dome_2',
// 'IDM_25',
// 'rungotti',
// 'runpurp',
// 'interference',
// 'IDM_Strafe2',
// 'fe-dome_1_rox',
// 'rocketlauncher',
// 'bug10',
// 'lucy-j4n',
// 'lucy-endi',
// 'dfwc2016-round_5',
// 'Idm_HypaH',
// 'kairos-dlc1',
// 'leftov',
// 'lucy-vchrkn',
// 'rocketque13',
// 'r7-ivyx8',
// 'sm9_kairos',
// 'Runvixen',
// 'runaway_test',
// 'Bug-gothic',
// 'mikrobrun3',
// 'rmn_springy',
// 'fm-2',
// 'dfwc03-2',
// 'fried-pickle',
// 'bug-trails3',
// 'plakill',
// 'fst02',
// 'bug-woody',
// 'ct0002',
// 'BardoK-Ralf',
// 'effect-172',
// 'ds_vs_fks',
// 'cityrocket',
// 'spr-gpl',
// 'bug54',
// 'r7-silence',
// 'nood-mu-cki',
// 'rocketque12',
// 'effect-run4',
// 'bgcomp002',
// 'pornstar-afu',
// 'lovet-arcaon-rocket',
// 'sdc45',
// 'gamoleum',
// 'acc_celerity',
// 'pornstar-plasmarum',
// 'arcticka_mapka',
// 'lucyfrutty-keanex',
// 'cpu-egypt',
// 'bes_vs_Sp00c7ER',
// 'biotrix-cavesrlfix',
// 'wura-run02',
// 'ruined-praet',
// 'rdfcomp044',
// 'cjscomp30_4',
// 'kiccel_cup05',
// 'cjscomp008',
// 'NtComp003',
// 'poon-mitt',
// 'bug-junk',
// 'biotrix-wcw',
// 'kool_simple4_rox',
// 'eyesore',
// 'r7-nina1',
// 'PDM02_SzakaL',
// 'cj_war4',
// 'run_un-dead_enter',
// 'pornstar-run8',
// 'elco-flo',
// 'poon-train-combo',
// 'r7-reanimated',
// 'bramble',
// 'biotrix-egypt',
// 'tutty-wrun',
// 'killua-hxh',
// 'gothrockets',
// 'cruggle',
// 'elevation-run',
// 'Triqstyle',
// 'tutty-03',
// 'eksha_kool',
// 'bdfcomp016',
// 'frcup35',
// 'biotrix-mdk',
// 'lmao',
// 'r7-k3t',
// 'nlrun-3',
// 'biotrix-gold',
// 'kool_scigypt',
// 'nemix_run01',
// 'yotoon-grid',
// 'toptuk-3',
// 'sdc50-07',
// 'bdfcomp037',
// 'poon-tech',
// 'u1p_neon',
// 'elco-woody',
// 'kool_slart',
// 'porndok-4',
// 'pornstar-nc3',
// 'ifx_run6',
// 'dart-run8wce',
// 'cruton2',
// 'uN-DeaD013',
// 'biotrix-base',
// плюс карты с новых варкапов
