import { Difficulty } from '../enums/difficulty.enum';
import { MapInterface } from '../interfaces/map.interface';

export const maps: MapInterface[] = [
    {
        name: 'r2fast',
        difficulty: Difficulty.MEDIUM,
        weapons: 'U',
    },
    {
        name: 'nemix_run01',
        difficulty: Difficulty.MEDIUM,
        weapons: 'GRP',
    },
    {
        name: 'tuffrun',
        difficulty: Difficulty.HARD,
        weapons: 'U',
    },
    {
        name: 'unwind_run02',
        difficulty: Difficulty.MEDIUM,
        weapons: 'GRPB',
    },
    {
        name: 'run_quake',
        difficulty: Difficulty.MEDIUM,
        weapons: 'U',
    },
    {
        name: 'run3-diche',
        difficulty: Difficulty.EASY,
        weapons: 'GP',
    },
    {
        name: 'imoor_run01',
        difficulty: Difficulty.VERY_HARD,
        weapons: 'GRP',
    },
    {
        name: 'score',
        difficulty: Difficulty.MEDIUM,
        weapons: 'GRP',
    },
    {
        name: 'dsrun2',
        difficulty: Difficulty.EASY,
        weapons: 'U',
    },
    {
        name: 'czsk2009-impulse',
        difficulty: Difficulty.MEDIUM,
        weapons: 'GRPB',
    },
    {
        name: 'elco-egy',
        difficulty: Difficulty.VERY_HARD,
        weapons: 'GRPB',
    },
    {
        name: 'imoor_run07',
        difficulty: Difficulty.MEDIUM,
        weapons: 'U',
    },
    {
        name: 'pornstar-8percent',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'pornstar-quickie1',
        difficulty: Difficulty.EASY,
        weapons: 'U',
    },
    {
        name: 'pdm01_TymoN',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RPI',
    },
    {
        name: 'run_Swordfish',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RPB',
    },
    {
        name: 'alphamap',
        difficulty: Difficulty.EASY,
        weapons: 'RP',
    },
    {
        name: 'frcup34',
        difficulty: Difficulty.HARD,
        weapons: 'RP',
    },
    {
        name: 'ghost-pornstar2',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'elco-maze',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'killua-hykon',
        difficulty: Difficulty.MEDIUM,
        weapons: 'R',
    },
    {
        name: 'termite',
        difficulty: Difficulty.HARD,
        weapons: 'P',
    },
    {
        name: 'yotoon-glados',
        difficulty: Difficulty.HARD,
        weapons: 'U',
    },
    {
        name: 'mAndArin_run2',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RP',
    },
    {
        name: '2fastcomp001',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'RLP',
    },
    {
        name: 'effect-bfgrun',
        difficulty: Difficulty.MEDIUM,
        weapons: 'B',
    },
    {
        name: 'fu3l3d_rocket',
        difficulty: Difficulty.EASY,
        weapons: 'R',
    },
    {
        name: 'cwc01_1',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RGP',
    },
    {
        name: 'poon-udc',
        difficulty: Difficulty.HARD,
        weapons: 'RP',
    },
    {
        name: 'kairos-machine',
        difficulty: Difficulty.EASY,
        weapons: 'SBH',
    },
    {
        name: 'r7-spling',
        difficulty: Difficulty.EASY,
        weapons: 'RGBLP',
    },
    {
        name: 'n3ur0_icebase',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'ddc2018-stomp',
        difficulty: Difficulty.VERY_HARD,
        weapons: 'RI',
    },
    {
        name: 'ddc2018-abydos',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RGP',
    },
    {
        name: 'ddc2018-enigma',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'ddc2018-amaranth',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RGP',
    },
    {
        name: 'ddc2018-apex',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RGP',
    },
    {
        name: 'ddc2018-countach',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RG',
    },
    {
        name: 'ddc2018-medieva',
        difficulty: Difficulty.MEDIUM,
        weapons: 'RGPB',
    },
    {
        name: 'ddc2018-tryhoard',
        difficulty: Difficulty.HARD,
        weapons: 'RGP',
    },
    {
        name: 'cruton2-icy',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'ghost-city',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'daan-spacerox',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'R',
    },
    {
        name: 'stammer-rocketcave',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'R',
    },
    {
        name: 'pento-slick',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'coldrun',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'RP',
    },
    {
        name: 'biotrix-sea',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'f1o_s1',
        difficulty: Difficulty.VERY_EASY,
        weapons: 'U',
    },
    {
        name: 'thd-final09',
        difficulty: Difficulty.HARD,
        weapons: 'RGP',
    },
    // {
    //     name: 'th0ca-isback',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'j4n_mucki',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'warcup50-3',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'xLarve_df09',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'bdfcomp026',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'gdfcomp11',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'furthy_roomz',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'warrior-rj1',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'kiccel_cup04',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'sdc39',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'q3dfrun',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'frcup42',
    //     difficulty: Difficulty.VERY_EASY,
    // },
    // {
    //     name: 'bdfcomp012',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'Nlrun-1',
    //     difficulty: Difficulty.VERY_HARD,
    // },
    // {
    //     name: 'Hydrosorbic',
    //     difficulty: Difficulty.VERY_HARD,
    // },
    // {
    //     name: 'cruton3',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'gpl-gypt',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'cross-03-aren',
    //     difficulty: Difficulty.VERY_HARD,
    // },
    // {
    //     name: 'j4n_yotoon',
    //     difficulty: Difficulty.VERY_EASY,
    // },
    // {
    //     name: 'inder-junk',
    //     difficulty: Difficulty.MEDIUM,
    // },
    // {
    //     name: 'e-penetration',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'rockarolla9',
    //     difficulty: Difficulty.EASY,
    // },
    // {
    //     name: 'kabcorp-jel',
    //     difficulty: Difficulty.HARD,
    // },
    // 'effect-combo',
    // '0ups-rocketrun1',
    // 'grottorush',
    // 'Discord',
    // 'cmc06_th0ca',
    // 'pornstar-thickwoman',
    // 'sdc01',
    // 'acc_cake',
    // 'IDM_Aectroner',
    // 'mistes-depot',
    // 'Pharaohmones',
    // 'crem_brew_lay',
    // 'stalker-mirai',
    // 'j4n_run3',
    // 'IDM_Sobaken',
    // 'asda-kartta',
    // 'bomfunk2',
    // 'effect-hyper',
    // 'Rocketque11',
    // 'geto',
    // 'in_memory_of_gloom',
    // 'mistes-wprun04',
    // 'Hypertension',
    // 'mistes-wprun05',
    // 'inder-strangeland',
    // 'xLarve_df19',
    // 'runzedder-4',
    // 'r7-jel',
    // 'kabcorp-sousix_is_dead',
    // 'rjrunv2',
    // 'cupquake',
    // 'marvin-waffenlauf2',
    // 'spr-gpl',
    // 'nood-momentum',
    // 'biscuit',
    // 'enz-02',
    // 'cruton6-rox',
    // 'ThotExpress',
    // 'th0ca-boring',
    // 'run124',
    // 'nood-momentum2',
    // 'xLarve_df20',
    // 'torner2015-heroo',
    // 'torner2015-reflex',
    // 'monorun',
    // 'gloom_comp01',
    // 'xt4zy-shorty_huerty01',
    // 'RDFCOMP054',
    // 'tenuous',
    // 'runstolfer-5',
    // 'gothrockets',
    // 'DFru_mappers_01',
    // 'rundsi',
    // 'run139',
    // 'kairos-returns',
    // 'nood-4_den',
    // 'Dark-Temple',
    // 'lg21',
    // 'warcup144',
    // 'ruyn',
    // 'imoor_run08',
    // 'mistes-wprun06',
    // 'dfcup09',
    // 'runtomb',
    // 'RunMesta',
    // 'j4n_Strangeland_FULL',
    // 'l1th-inder',
    // 'IDM_frAkIR',
    // 'fe-run_1_rox',
    // 'run-brickstonerocket',
    // 'nood-acab',
    // 'xt4zy_4QL',
    // 'j4n_hotrun',
    // 'Hellescape',
    // 'kabcorp-effect',
    // 'ropg',
    // 'fe-dome_2',
    // 'IDM_25',
    // 'rungotti',
    // 'runpurp',
    // 'interference',
    // 'IDM_Strafe2',
    // 'fe-dome_1_rox',
    // 'rocketlauncher',
    // 'bug10',
    // 'lucy-j4n',
    // 'lucy-endi',
    // 'dfwc2016-round_5',
    // 'Idm_HypaH',
    // 'kairos-dlc1',
    // 'leftov',
    // 'lucy-vchrkn',
    // 'rocketque13',
    // 'r7-ivyx8',
    // 'sm9_kairos',
    // 'Runvixen',
    // 'runaway_test',
    // 'Bug-gothic',
    // 'mikrobrun3',
    // 'rmn_springy',
    // 'fm-2',
    // 'dfwc03-2',
    // 'fried-pickle',
    // 'bug-trails3',
    // 'plakill',
    // 'fst02',
    // 'bug-woody',
    // 'ct0002',
    // 'BardoK-Ralf',
    // 'effect-172',
    // 'ds_vs_fks',
    // 'cityrocket',
    // 'spr-gpl',
    // 'bug54',
    // 'r7-silence',
    // 'nood-mu-cki',
    // 'rocketque12',
    // 'effect-run4',
    // 'bgcomp002',
    // 'pornstar-afu',
    // 'lovet-arcaon-rocket',
    // 'sdc45',
    // 'gamoleum',
    // 'acc_celerity',
    // 'pornstar-plasmarum',
    // 'arcticka_mapka',
    // 'lucyfrutty-keanex',
    // 'cpu-egypt',
    // 'bes_vs_Sp00c7ER',
    // 'biotrix-cavesrlfix',
    // 'wura-run02',
    // 'ruined-praet',
    // 'rdfcomp044',
    // 'cjscomp30_4',
    // 'kiccel_cup05',
    // 'cjscomp008',
    // 'NtComp003',
    // 'poon-mitt',
    // 'bug-junk',
    // 'biotrix-wcw',
    // 'kool_simple4_rox',
    // 'eyesore',
    // 'r7-nina1',
    // 'PDM02_SzakaL',
    // 'cj_war4',
    // 'run_un-dead_enter',
    // 'pornstar-run8',
    // 'elco-flo',
    // 'poon-train-combo',
    // 'r7-reanimated',
    // 'bramble',
    // 'biotrix-egypt',
    // 'tutty-wrun',
    // 'killua-hxh',
    // 'gothrockets',
    // 'cruggle',
    // 'elevation-run',
    // 'Triqstyle',
    // 'tutty-03',
    // 'eksha_kool',
    // 'bdfcomp016',
    // 'frcup35',
    // 'biotrix-mdk',
    // 'lmao',
    // 'r7-k3t',
    // 'nlrun-3',
    // 'biotrix-gold',
    // 'kool_scigypt',
    // 'nemix_run01',
    // 'yotoon-grid',
    // 'toptuk-3',
    // 'sdc50-07',
    // 'bdfcomp037',
    // 'poon-tech',
    // 'u1p_neon',
    // 'elco-woody',
    // 'kool_slart',
    // 'porndok-4',
    // 'pornstar-nc3',
    // 'ifx_run6',
    // 'dart-run8wce',
    // 'cruton2',
    // 'uN-DeaD013',
    // 'biotrix-base',
    // плюс карты с новых варкапов
];
